Repository wazo-platform/wazo-auth-keys, pull requests merged in 2021-04, with the labels that each got.

#38 add zuul
  zuul.yaml
Labels: mergeit

#37 add wazo-auth config file with predefined policies
  etc/wazo-auth/conf.d/50-wazo-default-policies.yml
Labels: mergeit

#39 Pull request for more-zuul-check
  integration_tests/suite/test_service_update.py
  wazo_auth_keys/commands/service.py
  wazo_auth_keys/tests/test_chainmap.py
  zuul.yaml
Labels: auto-merge

#41 default-user-policy: restrict token expiration events
  etc/wazo-auth/conf.d/50-wazo-default-policies.yml
Labels: mergeit

#42 add missing agents statistic access
  etc/wazo-auth/conf.d/50-wazo-default-policies.yml
Labels: mergeit

#43 test: use explicit ipv4 addr to connect docker
  integration_tests/suite/helpers/base.py
Labels: auto-merge, mergeit
